//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        public int CuotaId { get; set; }
        public int VentaId { get; set; }
        public decimal MontoCuota { get; set; }
        public int NumeroDeCuota { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
