//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoStock
    {
        public int MovimientoStockId { get; set; }
        public int ArticuloId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int StockAnterior { get; set; }
        public int Cantidad { get; set; }
        public int StockNuevo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
