//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int VentaId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaDePago { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
    }
}
