//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoAireAcondicionado
    {
        public int IdTrabajo { get; set; }
        public string DescripcionTrabajo { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> Precio { get; set; }
       
    }
}
