//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VentaId { get; set; }
        public int ClientId { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Talle { get; set; }
        public int FormaDePagoId { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeCancelacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cuotas { get; set; }
    }
}
