//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VentaId { get; set; }
        public int ClientId { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Talle { get; set; }
        public int FormaDePagoId { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeCancelacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
