//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaCredimax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentaCredimax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Comprobante de Venta&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: sans-serif;
        ///      background-color: #f0f0f0; /* Gris claro */
        ///    }
        ///
        ///    .header {
        ///      margin-bottom: 20px;
        ///    }
        ///
        ///    .header p {
        ///      margin: 5px 0;
        ///    }
        ///
        ///    table {
        ///      width: 100%;
        ///      border-collapse: collapse;
        ///    }
        ///
        ///    th, td {
        ///      border: 1px solid #ddd;
        ///      padding: 8px;
        ///      text-align: left;
        ///    }
        ///
        ///    th {
        ///      background-color: #f2f2f2;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComprobanteDeVenta {
            get {
                return ResourceManager.GetString("ComprobanteDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Recibo de Pago&lt;/title&gt;
        ///    &lt;script src=&quot;https://cdn.tailwindcss.com&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;bg-white p-4&quot;&gt;
        ///    &lt;div class=&quot;max-w-2xl mx-auto border border-black p-4&quot;&gt;
        ///        &lt;div class=&quot;flex justify-between items-center mb-4&quot;&gt;
        ///            &lt;h1 class=&quot;text-2xl font-bold text-blue-700&quot;&gt;RECIBO DE PAGO&lt;/h1&gt;
        ///            &lt;div class=&quot;text-right&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboDeCuota {
            get {
                return ResourceManager.GetString("ReciboDeCuota", resourceCulture);
            }
        }
    }
}
