//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaCredimax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentaCredimax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Comprobante de Venta&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .container {
        ///            max-width: 42rem;
        ///            margin: 0 auto;
        ///            border: 1px solid black;
        ///            padding: 1rem;
        ///            padding-bottom: 4px;
        ///        }
        ///
        ///        .header {
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .header h1 {
        ///            color: #1D4ED8;
        ///            text-align: center;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComprobanteDeVenta {
            get {
                return ResourceManager.GetString("ComprobanteDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Recibo de Pago&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: white;
        ///            padding: 1rem;
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .container {
        ///            max-width: 42rem;
        ///            margin: 0 auto;
        ///            border: 1px solid black;
        ///            padding: 1rem;
        ///        }
        ///
        ///        .header  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboDeCuota {
            get {
                return ResourceManager.GetString("ReciboDeCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Comprobante de Venta&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        .container {
        ///            max-width: 42rem;
        ///            margin: 0 auto;
        ///            border: 1px solid black;
        ///            padding: 1rem;
        ///            padding-bottom: 4px;
        ///        }
        ///
        ///        .header {
        ///            margin-bottom: 20px;
        ///        }
        ///
        ///        .header h1 {
        ///            color: #1D4ED8;
        ///            text-align: center;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VentasPorCliente {
            get {
                return ResourceManager.GetString("VentasPorCliente", resourceCulture);
            }
        }
    }
}
